# Generated by Django 4.2.13 on 2024-05-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='creator',
        ),
    ]
