# Generated by Django 4.2.13 on 2024-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' вознаграждение'),
        ),
    ]
